### ISSUE TITLE
通知浮层溢出

### ISSUE THREAD

**Issue by kxxoling** [zerqu/qingcheng#11]
今天登录的时候发现这样的情况：
![qingcheng](https://cloud.githubusercontent.com/assets/1227139/13666987/4396bc38-e6ef-11e5-8a45-efa65a1de606.png)

通知样式出错，占据的行高过多以致溢出，两个问题都应该修复一下。

另外就是可以考虑下在前端合并下系统通知。

**Comment by lepture** [comment]
最近在用 vuex，觉得用这个会更方便，有空我把项目再整理一下。

**Comment by kxxoling** [comment]
@lepture 好像最近哪次提交把不少地方的样式都弄乱了。。

**Comment by kxxoling** [comment]
Fixed: https://github.com/zerqu/qingcheng/pull/15
