### ISSUE TITLE
注册的时候报错

### ISSUE THREAD

**Issue by hym116** [zerqu/qingcheng#14]
./src/components/LoginForm.vue:102 Uncaught TypeError: (0 , _utils2.default) is not a function

**Comment by kxxoling** [comment]
@hym116 很奇怪，102 行已经是样式了。而且我刚刚测试了线上的注册是 OK 的。

**Comment by hym116** [comment]
哦，这样子的，谢谢您耐心的解答~

**Comment by kxxoling** [comment]
@hym116 不客气。如果这个问题已经解决的话，就把 issue 关闭吧。
