### ISSUE TITLE
关于删除了route.js的问题

### ISSUE THREAD

**Issue by hym116** [zerqu/qingcheng#17]
记得您以前的的版本里面有路由配置的，在route.js里面，index.js里是这样子的：registerRouters(router);
可是新版本里做了改动，删除了路由配置文件，然后index.js里是这样子的：
import views from './views';
router.map(views)
请问这是为什么呢？
我是新手……望能解答一下，谢谢~

**Comment by lepture** [comment]
coz it's more elegant

**Comment by 0xReturn** [comment]
因为路由会非常多，所以通常都会弄一个文件单独存放路由配置。

1.  src/views/index.js 里面，作者export了路由的配置对象  (行13)
2.  src/index.js 里面import之前导出的路由配置对象  (行37)
